dist: xenial
language: cpp
branches:
  only:
    - master
before_script:
  # add modern repo for loading boost 1.67 packages, want thread_pool
  - sudo cp config_travis/cosmic_packages.pref /etc/apt/preferences.d/cosmic_package-repo.pref
  - sudo cp config_travis/cosmic.list          /etc/apt/sources.list.d/cosmic.list

  # install boost 1.67 from cosmic repo
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev libprotobuf-dev protobuf-compiler -t cosmic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libpq-dev # and may be postgresql
      - postgresql-server-dev-all
script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cd protocol
  # that is how to generate files for serialization/deserialization
  - protoc  --cpp_out=../server/src/proto --python_out=../server/tests  messages.proto

  - cd build
  - cmake ..
  - cmake --build .
